# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="mywifi"
CIRCUITPY_WIFI_PASSWORD="mypass"

# To enable the web workflow. Change this too!
# Leave the User field blank in the browser.
CIRCUITPY_WEB_API_PASSWORD="mypass"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_INSTANCE_NAME="ESP32-C3-0001"
